name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm compile --noEmit
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
